// Postgres schema for the TEAM flavor (Cloudflare Worker + Neon).
//
// Ported from the original closed-source Arlo deployment. The local flavor uses
// schema.sqlite.ts instead (no `users`, no `project_state_cache`). Both export
// the same table identifiers so the row→DTO mappers in mappers.ts apply to both.

import { sql } from "drizzle-orm"
import { index, integer, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core"

// One row per teammate. The raw API key is generated by the create-user script,
// HMAC-hashed with API_KEY_HMAC_SECRET, then stored as apiKeyHash. The raw key
// is shown to the operator once and never persisted.
export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  apiKeyHash: text("api_key_hash").notNull().unique(),
  // GitHub login for this teammate. Lets an agent claiming an issue assign the
  // *human* (not the agent) on GitHub. Nullable for non-GitHub identities.
  githubUsername: text("github_username"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
})

// One row per active or recently active Claude Code instance, keyed by a stable
// per-checkout `cwdHash` so the SessionStart hook and the long-lived MCP shim
// converge on the same row.
export const agentSessions = pgTable(
  "agent_sessions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    agentLabel: text("agent_label").notNull(),
    // Stable per-cwd identifier: sha256(gitToplevel)[:16].
    cwdHash: text("cwd_hash").notNull(),
    projectScope: text("project_scope"),
    currentFocus: text("current_focus"),
    claimedIssueNumber: integer("claimed_issue_number"),
    claimedRepoFullName: text("claimed_repo_full_name"),
    status: text("status", { enum: ["active", "idle", "gone"] })
      .notNull()
      .default("active"),
    startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
  },
  (t) => [
    index("agent_sessions_user_id_idx").on(t.userId),
    index("agent_sessions_last_seen_idx").on(t.lastSeenAt),
    index("agent_sessions_status_idx").on(t.status),
    // At most one *live* session per (user, cwd). The checkin endpoint upserts
    // against this partial unique index, so the hook and the shim converge on a
    // single row even under a simultaneous race. 'gone' rows remain for history.
    uniqueIndex("agent_sessions_user_cwd_live_uq")
      .on(t.userId, t.cwdHash)
      .where(sql`status <> 'gone'`),
  ],
)

// "What files are other sessions touching." One row per (session, path); the
// write path upserts on that pair and bumps `touchedAt`. The janitor prunes
// rows older than 24h.
export const fileActivity = pgTable(
  "file_activity",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    agentSessionId: uuid("agent_session_id")
      .notNull()
      .references(() => agentSessions.id),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    // Repo-relative (the git toplevel prefix is stripped before reporting).
    filePath: text("file_path").notNull(),
    repoFullName: text("repo_full_name"),
    tool: text("tool", { enum: ["Write", "Edit", "MultiEdit", "NotebookEdit"] }).notNull(),
    touchedAt: timestamp("touched_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("file_activity_touched_at_idx").on(t.touchedAt),
    index("file_activity_session_idx").on(t.agentSessionId),
    uniqueIndex("file_activity_session_path_uq").on(t.agentSessionId, t.filePath),
  ],
)

// Append-only log. Every claim, decision, handoff, escalation gets a row.
export const auditEvents = pgTable(
  "audit_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    eventType: text("event_type").notNull(),
    userId: uuid("user_id").references(() => users.id),
    agentSessionId: uuid("agent_session_id").references(() => agentSessions.id),
    payload: text("payload"), // JSON, free-form
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("audit_events_type_idx").on(t.eventType),
    index("audit_events_created_at_idx").on(t.createdAt),
  ],
)

// Typed shared decisions, append-only with supersedes pointers. The current
// decision for a topic is the most recent row with status='active' sharing a key.
export const decisions = pgTable(
  "decisions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    decisionKey: text("decision_key").notNull(),
    content: text("content").notNull(),
    decisionType: text("decision_type", {
      enum: ["architecture", "tooling", "process", "scope", "other"],
    })
      .default("other")
      .notNull(),
    projectScope: text("project_scope"),
    authorUserId: uuid("author_user_id").references(() => users.id),
    authorAgentSessionId: uuid("author_agent_session_id").references(() => agentSessions.id),
    status: text("status", { enum: ["active", "pending", "superseded", "rejected"] })
      .notNull()
      .default("active"),
    supersedes: uuid("supersedes").references((): any => decisions.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("decisions_key_idx").on(t.decisionKey),
    index("decisions_status_idx").on(t.status),
    index("decisions_created_at_idx").on(t.createdAt),
    // At most one *active* decision per key — the "conflicts are loud" promise
    // as a DB-level guarantee. Write paths treat a violation as a 409 conflict,
    // which also closes the select-then-insert race over neon-http.
    uniqueIndex("decisions_active_key_uq")
      .on(t.decisionKey)
      .where(sql`status = 'active'`),
  ],
)

// A soft layer over GitHub Issues. The canonical assignment lives in GitHub; the
// claim row gives low-latency cross-agent visibility before GitHub propagates.
export const taskClaims = pgTable(
  "task_claims",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    repoFullName: text("repo_full_name").notNull(),
    issueNumber: integer("issue_number").notNull(),
    claimedByUserId: uuid("claimed_by_user_id")
      .notNull()
      .references(() => users.id),
    claimedByAgentSessionId: uuid("claimed_by_agent_session_id").references(() => agentSessions.id),
    status: text("status", {
      enum: ["claimed", "in_progress", "pr_open", "released", "completed"],
    })
      .notNull()
      .default("claimed"),
    prNumber: integer("pr_number"),
    notes: text("notes"),
    claimedAt: timestamp("claimed_at", { withTimezone: true }).defaultNow().notNull(),
    lastActivityAt: timestamp("last_activity_at", { withTimezone: true }).defaultNow().notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  },
  (t) => [
    index("task_claims_repo_issue_idx").on(t.repoFullName, t.issueNumber),
    index("task_claims_status_idx").on(t.status),
    index("task_claims_expires_idx").on(t.expiresAt),
    // At most one *live* claim per (repo, issue): enables atomic
    // INSERT ... ON CONFLICT DO NOTHING.
    uniqueIndex("task_claims_live_uq")
      .on(t.repoFullName, t.issueNumber)
      .where(sql`status in ('claimed','in_progress','pr_open')`),
  ],
)

// Structured agent-to-agent or agent-to-human context transfers.
export const handoffs = pgTable(
  "handoffs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fromAgentSessionId: uuid("from_agent_session_id")
      .notNull()
      .references(() => agentSessions.id),
    toAgentSessionId: uuid("to_agent_session_id").references(() => agentSessions.id),
    toUserId: uuid("to_user_id").references(() => users.id),
    projectScope: text("project_scope"),
    context: text("context").notNull(),
    state: text("state"), // serialized JSON
    suggestedNextActions: text("suggested_next_actions"),
    status: text("status", { enum: ["pending", "accepted", "completed", "expired"] })
      .notNull()
      .default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => [
    index("handoffs_status_idx").on(t.status),
    index("handoffs_to_agent_idx").on(t.toAgentSessionId),
    index("handoffs_to_user_idx").on(t.toUserId),
  ],
)

// Cache of GitHub Projects board state, refreshed by cron to respect rate
// limits. Team flavor only.
export const projectStateCache = pgTable(
  "project_state_cache",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    repoFullName: text("repo_full_name").notNull(),
    projectNumber: integer("project_number").notNull(),
    snapshot: text("snapshot").notNull(),
    fetchedAt: timestamp("fetched_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [uniqueIndex("project_state_cache_repo_project_uq").on(t.repoFullName, t.projectNumber)],
)

export type User = typeof users.$inferSelect
export type AgentSessionRow = typeof agentSessions.$inferSelect
export type FileActivityRow = typeof fileActivity.$inferSelect
export type AuditEventRow = typeof auditEvents.$inferSelect
export type DecisionRow = typeof decisions.$inferSelect
export type TaskClaimRow = typeof taskClaims.$inferSelect
export type HandoffRow = typeof handoffs.$inferSelect
export type ProjectStateCacheRow = typeof projectStateCache.$inferSelect
